from PySide6.QtCore import Qt, QSize

WIDTH = 500
HEIGHT = 500
BUTTON_WIDTH = 100
BUTTON_HEIGHT = 50
SPACE = 20
DEFAULT_CELL_SIZE = 50

GL_BACKGROUND_COLOR = Qt.white
GL_LINE_COLOR = Qt.black
GL_LINE_THICKNESS = 2
GL_POINT_RADIUS = 10
GL_POINT_COLOR_START = Qt.green
GL_POINT_COLOR_END = Qt.red

MAIN_BACKGROUND_COLOR = "white"
BUTTON_SIZE = QSize(BUTTON_WIDTH, BUTTON_HEIGHT)
